#!/bin/bash
mkdir -p /tmp/.cache/hardhat-nodejs/compilers-v2/linux-amd64 & cp -a ../usr/local/node-cache-packages/node_modules/. ./node_modules/

node build.js solc-linux-amd64-v0.8.5+commit.a4f2e591
